# Generated by Django 6.1 on 2026-08-11 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(default='Actor', max_length=100)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(default=120)),
                ('release_date', models.DateField(db_index=True)),
                ('age_rating', models.CharField(choices=[('U', 'Universal'), ('UA', 'Parental Guidance'), ('A', 'Adults Only'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted')], default='UA', max_length=10)),
                ('trailer_youtube_url', models.URLField(help_text='YouTube URL or embed link', max_length=500)),
                ('poster_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800', max_length=500)),
                ('backdrop_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('avg_rating', models.FloatField(db_index=True, default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.language')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=150)),
                ('cast_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_appearances', to='movies.castmember')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_movi_title_652549_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['avg_rating'], name='movies_movi_avg_rat_6515c7_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['total_bookings'], name='movies_movi_total_b_864760_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active'], name='movies_movi_is_acti_00ce83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermovieview',
            unique_together={('user', 'movie')},
        ),
    ]
