# Generated by Django 6.1 on 2026-08-11 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='theaters.city')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('screen_type', models.CharField(choices=[('2D', 'Standard 2D'), ('3D', 'RealD 3D'), ('IMAX', 'IMAX 3D'), ('4DX', '4DX Motion')], default='2D', max_length=10)),
                ('total_seats', models.IntegerField(default=120)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theaters.theater')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5)),
                ('number', models.IntegerField()),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('VIP', 'VIP Recliner')], default='REGULAR', max_length=15)),
                ('base_price', models.DecimalField(decimal_places=2, default=250.0, max_digits=8)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theaters.screen')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('screen', 'row', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city'], name='theaters_th_city_id_5510f9_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['name'], name='theaters_th_name_1fa4e9_idx'),
        ),
    ]
